import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { sites } from '@openai/sites-vite-plugin';
import tailwindcss from '@tailwindcss/postcss';
import vinext from 'vinext';
import { defineConfig } from 'vite';

const SITE_CREATOR_PLACEHOLDER_DATABASE_ID =
  '00000000-0000-4000-8000-000000000000';

// `.openai/hosting.json` is machine-local (git-ignored) and generated by
// `scripts/ensure-hosting.mjs`. It only exists after the Sites setup writes
// real bindings, so load it defensively and fall back to "no bindings" to
// keep fresh clones able to run `npm run dev` and `npm run build`.
type HostingConfig = { d1?: string | null; r2?: string | null };

function loadHostingConfig(): HostingConfig {
  const hostingPath = fileURLToPath(
    new URL('./.openai/hosting.json', import.meta.url),
  );
  if (!existsSync(hostingPath)) return { d1: null, r2: null };
  try {
    const parsed = JSON.parse(readFileSync(hostingPath, 'utf8')) as HostingConfig;
    return {
      d1: typeof parsed?.d1 === 'string' ? parsed.d1 : null,
      r2: typeof parsed?.r2 === 'string' ? parsed.r2 : null,
    };
  } catch {
    return { d1: null, r2: null };
  }
}

// macOS Seatbelt blocks FSEvents, so Codex previews need polling for HMR.
const isCodexSeatbeltSandbox = process.env.CODEX_SANDBOX === 'seatbelt';

export default defineConfig(async () => {
  // Keep Wrangler and Miniflare state project-local. These are non-secret tool
  // settings; application environment belongs in ignored `.env*` files.
  process.env.WRANGLER_WRITE_LOGS ??= 'false';
  process.env.WRANGLER_LOG_PATH ??= '.wrangler/logs';
  process.env.MINIFLARE_REGISTRY_PATH ??= '.wrangler/registry';

  // Wrangler snapshots its log path while the Cloudflare plugin is imported.
  const { cloudflare } = await import('@cloudflare/vite-plugin');
  const hostingConfig = loadHostingConfig();

  const localBindingConfig = {
    main: 'vinext/server/fetch-handler',
    compatibility_flags: ['nodejs_compat'],
    d1_databases: hostingConfig.d1
      ? [
          {
            binding: hostingConfig.d1,
            database_name: 'site-creator-d1',
            database_id: SITE_CREATOR_PLACEHOLDER_DATABASE_ID,
          },
        ]
      : [],
    r2_buckets: hostingConfig.r2
      ? [
          {
            binding: hostingConfig.r2,
            bucket_name: 'site-creator-r2',
          },
        ]
      : [],
  };

  return {
    css: { postcss: { plugins: [tailwindcss()] } },
    server: isCodexSeatbeltSandbox
      ? { watch: { useFsEvents: false, usePolling: true } }
      : undefined,
    plugins: [
      vinext(),
      sites(),
      cloudflare({
        viteEnvironment: { name: 'rsc', childEnvironments: ['ssr'] },
        config: localBindingConfig,
      }),
    ],
  };
});
